### ISSUE TITLE
failing installation

### ISSUE THREAD

**Issue by malikshi** [elestio/ws-monitoring#4]
@root/acme@3.1.0 postinstall /root/ws-monitoring/node_modules/@root/acme
node scripts/postinstall

internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module '/root/ws-monitoring/node_modules/@root/acme/scripts/postinstall'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
npm WARN ws-monitoring@1.0.2 scripts['server'] should probably be scripts['start'].
npm WARN ws-monitoring@1.0.2 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @root/acme@3.1.0 postinstall: `node scripts/postinstall`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @root/acme@3.1.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-01-05T21_05_03_887Z-debug.log

**Comment by jbenguira** [comment]
Hello

Please indicate what command you runned that produced this output.

**Comment by malikshi** [comment]
> Hello
> 
> Please indicate what command you runned that produced this output.

yup. it was `npm install` 2 days ago still no issue while doing the installation.

**Comment by jbenguira** [comment]
can you try this?

`npm install --ignore-scripts`

**Comment by malikshi** [comment]
> can you try this?
> 
> `npm install --ignore-scripts`

ok. it's work!
thank you

**Comment by jbenguira** [comment]
thanks for telling me, I have updated the readme :)

**Comment by malikshi** [comment]
thank you for fixing the problem. I will close the issues.
