### ISSUE TITLE
not running again

### ISSUE THREAD

**Issue by malikshi** [elestio/ws-monitoring#5]
I am installed with a manual version not using a binary version. after install `npm install --ignore-scripts` check files and no file appconfig.json, I'm ignoring it and try running with `token=123456789 ./run.sh` it running but can't access ws-monitoring at browser its says 404. no error with the binary version

**Comment by malikshi** [comment]
please add default appconfig.json. I tried to add manually appconfig.json from an older installation from my VPS and works.

**Comment by jbenguira** [comment]
Fixed :)
